# -*- coding: utf-8 -*-
"""Wordcloud-g2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158dYt_3IVSvoLg8kzYCb4KKTgHtADwbq
"""

# exercise 1
# author first member
# state: ongoing